COLOR_BARRA_SUPERIOR = "#1f2329"
COLOR_MENU_LATERAL = "#2a3138"
COLOR_CUERPO_PRINCIPAL = "#f1faff"
COLOR_MENU_CURSOR_ENCIMA = "#2f88c5"

#Colores de botones
COLOR_BOTON_AGREGAR = "#00ff00"
COLOR_BOTON_EDITAR = "#ffff00"
COLOR_BOTON_ELIMINAR = "#ff0000"
COLOR_BOTON_DEFAULT = "#ffffff"

#Fuente
FUENTE_LETRA = "Roboto"